# Generated by Django 6.0.5 on 2026-05-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='created',
        ),
    ]
